// Auto-generated & validated from Research Concept Master Sheet (D01-D25)
export interface MasterDomain {
  id: string;
  title: string;
  type: "Sector" | "Cross-cutting" | "Specialized";
  description: string;
  scopeBoundary: string;
  relatedDomainIds: string;
  whyExplore: string;
  contextSetting: string;
  stakeholders: string;
  processesToExplore: string;
  evidenceBasis: string;
  sdgRelevance: string;
  initialConcerns: string;
  nextAction: string;
}

export const MASTER_RESEARCH_DOMAINS: MasterDomain[] = [
  {
    "id": "D01",
    "title": "Agricultural Production and Farm Operations",
    "type": "Sector",
    "description": "Crop and livestock production, including day-to-day farm planning and operations before post-production distribution.",
    "scopeBoundary": "On-farm crop and livestock production; excludes food logistics (D09), fisheries production (D10), and environmental measurement as the primary purpose (D18).",
    "relatedDomainIds": "Related: D06, D09, D10",
    "whyExplore": "A major local livelihood with observable production, coordination, and record-keeping processes.",
    "contextSetting": "Crop and livestock farms, cooperatives, agriculture offices, agribusinesses",
    "stakeholders": "Farmers, farm workers, cooperatives, agriculture officers, agribusiness operators",
    "processesToExplore": "Production planning, crop and livestock monitoring, irrigation, input use, disease reporting, harvest records, farm records",
    "evidenceBasis": "PSA and Department of Agriculture background data support sector relevance; exact Iloilo source citations and local process evidence are still required.",
    "sdgRelevance": "",
    "initialConcerns": "Farmer or cooperative access; incomplete farm records; seasonal crop cycles; field travel; connectivity and device constraints.",
    "nextAction": "Secure one farm, cooperative, or agriculture-office partner and investigate one production process."
  },
  {
    "id": "D02",
    "title": "Teaching, Learning, and Academic Administration",
    "type": "Sector",
    "description": "Educational processes directly related to instruction, assessment, academic records, and school administration.",
    "scopeBoundary": "Teaching, learning, assessment, academic records, and administration; excludes accessibility (D14), student support (D15), work transition (D16), and local-language resources (D22) as primary concerns.",
    "relatedDomainIds": "Related: D14, D15, D16, D22",
    "whyExplore": "Students and educators are accessible, and many academic processes can be observed without assuming a technology.",
    "contextSetting": "Public and private schools, universities, classrooms, academic offices, learning environments",
    "stakeholders": "Students, teachers, academic coordinators, registrars, school administrators",
    "processesToExplore": "Instruction and learning-resource access, assessment, scheduling, enrollment, academic records, administrative workflows",
    "evidenceBasis": "DepEd policy and education statistics provide background; local school-process evidence and authorized records are not yet collected.",
    "sdgRelevance": "",
    "initialConcerns": "School approval; student privacy; timetable constraints; uneven facilities and connectivity; access to authorized process records.",
    "nextAction": "Choose one school or campus process and obtain the required approval before collecting baseline evidence."
  },
  {
    "id": "D03",
    "title": "Healthcare Service Delivery and Public Health Operations",
    "type": "Sector",
    "description": "Delivery and coordination of clinical, community, and administrative health services, without assuming access to clinical data.",
    "scopeBoundary": "Formal healthcare and public-health service workflows; excludes routine public safety (D13) and non-clinical student support (D15) as primary concerns.",
    "relatedDomainIds": "Related: D15",
    "whyExplore": "The domain contains consequential service problems, but meaningful study requires a formal health-sector access pathway.",
    "contextSetting": "Rural health units, clinics, hospitals, public-health offices, community health programs",
    "stakeholders": "Patients, healthcare workers, health administrators, public-health personnel",
    "processesToExplore": "Appointments, queues, referrals, non-clinical records, service coordination, supply workflows, public-health reporting",
    "evidenceBasis": "DOH and WVMC public information provide background; no accessible local workflow records are confirmed.",
    "sdgRelevance": "",
    "initialConcerns": "Formal health-facility partner; ethics and privacy approval; restricted clinical records; professional oversight; limited testing access.",
    "nextAction": "Seek a non-clinical health-workflow partner and an ethics/privacy route; otherwise keep the domain deferred."
  },
  {
    "id": "D04",
    "title": "Passenger Mobility and Local Transport Operations",
    "type": "Sector",
    "description": "Movement of passengers through local transport services and the operations that support commuting and mobility.",
    "scopeBoundary": "Passenger mobility and transport operations; excludes food freight and logistics (D09) and destination-service management (D11).",
    "relatedDomainIds": "Related: D11, D14",
    "whyExplore": "Commuter experiences and route conditions can be observed directly, while operational records may require permission.",
    "contextSetting": "Public-transport routes, terminals, urban corridors, campuses, parking areas",
    "stakeholders": "Students, commuters, drivers, operators, transport and traffic personnel",
    "processesToExplore": "Route use, waiting time, scheduling, passenger information, terminal operations, parking, mobility accessibility",
    "evidenceBasis": "Direct route observations and commuter interviews are feasible; TTMO or operator records are unverified.",
    "sdgRelevance": "",
    "initialConcerns": "TTMO or route-operator permission; route and traffic records may be unavailable; time and seasonal variation; field-observation safety.",
    "nextAction": "Conduct timed observations and commuter interviews on one route, then determine whether agency records are necessary."
  },
  {
    "id": "D05",
    "title": "Disaster Risk Reduction and Preparedness",
    "type": "Cross-cutting",
    "description": "Hazard-specific planning and coordinated action that reduce risk and prepare communities before and during emergencies.",
    "scopeBoundary": "Hazard-risk reduction and preparedness; excludes routine safety response (D13), environmental measurement (D18), and long-term adaptation planning (D19).",
    "relatedDomainIds": "Related: D13, D19",
    "whyExplore": "Communities face recurring hazards, and preparedness processes can be examined before selecting a technology.",
    "contextSetting": "Hazard-prone barangays, evacuation centers, schools, municipal DRRM operations",
    "stakeholders": "Residents, barangay officials, DRRMO personnel, responders, school safety staff",
    "processesToExplore": "Risk communication, preparedness planning, warning dissemination, evacuation planning, drills, relief readiness",
    "evidenceBasis": "PDRRMO/CDRRMO plans and public hazard information provide background; local process evidence is not yet collected.",
    "sdgRelevance": "",
    "initialConcerns": "PDRRMO or LGU permission; sensitive incident records; responder availability; emergency testing limits; hazard-specific scope.",
    "nextAction": "Select one hazard, locality, and preparedness process, then contact the relevant barangay or DRRMO."
  },
  {
    "id": "D06",
    "title": "Water Service and Resource Management",
    "type": "Sector",
    "description": "Management of water supply, distribution, use, routine quality oversight, and related service infrastructure.",
    "scopeBoundary": "Water supply, distribution, use, and service operations; excludes environmental measurement as the primary purpose (D18) and ecosystem-restoration management (D25).",
    "relatedDomainIds": "Related: D01, D08, D18, D25",
    "whyExplore": "Water-service conditions affect households and institutions and contain observable reporting and operational processes.",
    "contextSetting": "Communities, campuses, farms, water districts, shared water systems",
    "stakeholders": "Households, water providers, barangay officials, farmers, facility managers",
    "processesToExplore": "Supply scheduling, usage records, leak reporting, routine quality checks, pump and storage operations, service complaints",
    "evidenceBasis": "Water-agency and EMB sources provide background; provider records and water-quality evidence are unverified.",
    "sdgRelevance": "",
    "initialConcerns": "Utility or provider permission; restricted operational data; sampling and laboratory costs; seasonal variation; data ownership.",
    "nextAction": "Choose supply, quality, conservation, or irrigation, then secure the matching provider and evidence route."
  },
  {
    "id": "D07",
    "title": "Solid Waste Management Operations",
    "type": "Sector",
    "description": "Operational processes for segregating, collecting, recovering, recycling, treating, and disposing of solid waste.",
    "scopeBoundary": "Solid-waste operations; excludes environmental-condition measurement (D18) and ecosystem-restoration management (D25).",
    "relatedDomainIds": "Related: D12, D18, D25",
    "whyExplore": "Waste operations are visible in schools and communities and can produce measurable evidence at a bounded site.",
    "contextSetting": "Campuses, barangays, markets, collection points, materials recovery facilities",
    "stakeholders": "Households, students, facility staff, waste collectors, barangay and municipal personnel",
    "processesToExplore": "Segregation, collection scheduling, route operations, recovery and recycling, reporting, waste-volume recording",
    "evidenceBasis": "Official solid-waste policy and direct site audits can provide evidence; no local baseline or approved site is confirmed.",
    "sdgRelevance": "",
    "initialConcerns": "Barangay or campus permission; sanitation and PPE; consistent waste measurement; collector cooperation; behavior variability.",
    "nextAction": "Select one campus or barangay site, obtain permission, and conduct a baseline audit of one waste process."
  },
  {
    "id": "D08",
    "title": "Energy Use and Facility Energy Management",
    "type": "Sector",
    "description": "Operational monitoring and management of energy use, reliability, and efficiency in households and facilities.",
    "scopeBoundary": "Energy-use and facility-energy operations; excludes water-service operations (D06) and general residential maintenance (D17).",
    "relatedDomainIds": "Related: D06, D17",
    "whyExplore": "Energy use creates measurable costs and service concerns in homes, schools, businesses, and public facilities.",
    "contextSetting": "Homes, campuses, offices, small businesses, public buildings",
    "stakeholders": "Households, students, facility managers, business owners, power-service personnel",
    "processesToExplore": "Consumption records, peak-use assessment, equipment scheduling, outage reporting, facility energy assessment",
    "evidenceBasis": "DOE and distributor sources provide background; facility-level consumption and equipment records are unverified.",
    "sdgRelevance": "",
    "initialConcerns": "Meter or utility data access; electrical safety; hardware cost; facility permission; changing usage patterns.",
    "nextAction": "Choose one facility and one issue\u2014consumption, reliability, scheduling, or reporting\u2014and verify data and safety access."
  },
  {
    "id": "D09",
    "title": "Food Logistics and Supply-Chain Operations",
    "type": "Sector",
    "description": "Movement, handling, storage, and coordination of food after production through markets and consumers.",
    "scopeBoundary": "Post-production food movement, handling, storage, and coordination; excludes farm or fisheries production (D01, D10) and passenger transport (D04).",
    "relatedDomainIds": "Related: D01, D10, D23",
    "whyExplore": "Delays, spoilage, stock uncertainty, and coordination problems may be observable when one commodity chain is selected.",
    "contextSetting": "Farms and landing points, markets, cooperatives, storage areas, retailers, delivery routes",
    "stakeholders": "Producers, traders, vendors, transporters, retailers, consumers",
    "processesToExplore": "Inventory recording, storage conditions, shipment and delivery coordination, demand records, traceability, spoilage reporting",
    "evidenceBasis": "Sector reports and participant interviews may provide evidence; commodity-specific commercial records are unverified.",
    "sdgRelevance": "",
    "initialConcerns": "Commercially sensitive records; fragmented supply-chain data; seasonal supply; cold-storage access; participant availability.",
    "nextAction": "Reconsider only after one commodity-chain partner and one transition point are confirmed."
  },
  {
    "id": "D10",
    "title": "Fisheries and Aquaculture Production",
    "type": "Sector",
    "description": "Capture fisheries and farmed aquatic production, including operational and biological processes before distribution.",
    "scopeBoundary": "Fisheries and aquaculture production; excludes post-production food logistics (D09) and general environmental monitoring (D18).",
    "relatedDomainIds": "Related: D01, D09, D18, D25",
    "whyExplore": "The sector is locally important, but research requires sustained access to production sites, operators, or technical experts.",
    "contextSetting": "Fishing communities, fishponds, landing sites, hatcheries, aquaculture facilities",
    "stakeholders": "Fishers, fish farmers, fisheries officers, technical experts, coastal communities",
    "processesToExplore": "Production planning, feeding, stock and catch records, disease observation, harvest, landing records",
    "evidenceBasis": "BFAR, UPV, and SEAFDEC sources provide background; site datasets, expert labels, and laboratory access are unverified.",
    "sdgRelevance": "",
    "initialConcerns": "Sustained field-site and fisher access; BFAR, UPV, or SEAFDEC expert support; equipment and laboratory fees; weather and seasonality.",
    "nextAction": "Reconsider only after a fisheries partner, field site, expert, schedule, and total cost are confirmed."
  },
  {
    "id": "D11",
    "title": "Tourism Services and Destination Operations",
    "type": "Sector",
    "description": "Visitor-facing services and the operation and management of tourism destinations, accommodations, and activities.",
    "scopeBoundary": "Visitor and destination services; excludes passenger transport as the primary process (D04) and cultural safeguarding (D20).",
    "relatedDomainIds": "Related: D04, D14, D20",
    "whyExplore": "Local destinations allow observation of visitor and operator processes, subject to site cooperation and seasonality.",
    "contextSetting": "Heritage and natural sites, festivals, tourism offices, accommodations, transport terminals",
    "stakeholders": "Visitors, residents, tourism officers, guides, transport providers, local businesses",
    "processesToExplore": "Visitor information, bookings and inquiries, visitor flow, accessibility, feedback, site and destination operations",
    "evidenceBasis": "DOT and local-tourism reports provide background; site-specific visitor and process evidence is unverified.",
    "sdgRelevance": "",
    "initialConcerns": "Tourism-site and business permission; seasonality; visitor recruitment; commercially sensitive records; heritage and community sensitivity.",
    "nextAction": "Select one destination and one visitor or operator process, then confirm site cooperation."
  },
  {
    "id": "D12",
    "title": "Government Service Delivery and Administrative Workflows",
    "type": "Sector",
    "description": "Citizen-facing transactions and internal administrative workflows of government offices, independent of sector-specific program content.",
    "scopeBoundary": "Citizen-facing government transactions and administrative workflows; excludes sector-specific problems merely because an LGU operates the service.",
    "relatedDomainIds": "Related: D07, D13, D24",
    "whyExplore": "Citizens regularly use public offices, allowing investigation of service access, delays, routing, and transparency.",
    "contextSetting": "Barangay halls, municipal offices, service counters, public consultations",
    "stakeholders": "Citizens, barangay officials, municipal staff, applicants, civil-society groups",
    "processesToExplore": "Applications, permits, document requests, complaints, case routing, public information, feedback, processing-time recording",
    "evidenceBasis": "DILG, ARTA, and Citizen's Charter documents provide process baselines; actual local transaction data are unverified.",
    "sdgRelevance": "",
    "initialConcerns": "LGU permission; protected records; policy variation; staff workload; process ownership; Citizen's Charter may not reflect actual practice.",
    "nextAction": "Select one government transaction and office, then map the current process with authorized participants."
  },
  {
    "id": "D13",
    "title": "Community Safety and Emergency Response",
    "type": "Sector",
    "description": "Prevention, reporting, coordination, and response for routine community-safety incidents and emergencies not primarily focused on natural-hazard planning.",
    "scopeBoundary": "Routine safety-incident reporting and emergency response; excludes natural-hazard preparedness (D05) and long-term climate adaptation (D19).",
    "relatedDomainIds": "Related: D05, D12, D24",
    "whyExplore": "Safety reporting and response coordination are consequential but require careful handling of operational information.",
    "contextSetting": "Barangays, schools, public spaces, transport areas, emergency operations centers",
    "stakeholders": "Residents, barangay officials, responders, school safety staff, enforcement personnel",
    "processesToExplore": "Incident reporting, dispatch, public advisories, response coordination, resource status, after-action records",
    "evidenceBasis": "Public-safety policies and advisories provide background; incident and response records are restricted.",
    "sdgRelevance": "",
    "initialConcerns": "Sensitive incident and security data; agency permission; respondent safety; false or incomplete reports; no testing in real emergencies.",
    "nextAction": "Retain one safe public-information or coordination process and obtain an agency partner."
  },
  {
    "id": "D14",
    "title": "Accessibility and Inclusive Participation",
    "type": "Cross-cutting",
    "description": "Conditions and barriers affecting equitable access to digital services, communication, mobility, learning, and public participation.",
    "scopeBoundary": "Accessibility barriers and inclusive participation; excludes assuming assistive technology as the solution and excludes general education operations.",
    "relatedDomainIds": "Related: D02, D04, D11, D15, D22",
    "whyExplore": "Accessibility becomes researchable when representative users help define needs and evaluation criteria.",
    "contextSetting": "Schools, campuses, homes, public facilities, websites, mobile services",
    "stakeholders": "People with disabilities, caregivers, educators, accessibility advocates, service providers",
    "processesToExplore": "Accessibility assessment, digital navigation, communication access, wayfinding, service accommodation, usability evaluation",
    "evidenceBasis": "Accessibility standards and participatory evidence are appropriate; representative local evidence has not been collected.",
    "sdgRelevance": "",
    "initialConcerns": "Representative participant recruitment; informed consent; diverse accessibility needs; assistive-device availability; expert validation.",
    "nextAction": "Secure representative participants and a qualified accessibility validator before defining requirements."
  },
  {
    "id": "D15",
    "title": "Student Support Services and Academic Well-being",
    "type": "Specialized",
    "description": "Non-clinical academic, social, and support-service conditions affecting students' participation and ability to learn.",
    "scopeBoundary": "Non-clinical student-support and academic-well-being processes; excludes health diagnosis or treatment (D03) and general teaching processes (D02).",
    "relatedDomainIds": "Parent: D02; Related: D03, D14",
    "whyExplore": "The group can access students and observe service-discovery, workload, and support-process concerns.",
    "contextSetting": "Universities, schools, classrooms, student-service offices, online learning environments",
    "stakeholders": "Students, teachers, guidance personnel, student-affairs staff, parents or guardians when appropriate",
    "processesToExplore": "Workload coordination, support-service discovery, appointments, campus participation, referrals, follow-up",
    "evidenceBasis": "Student interviews, observation, and public service information may provide evidence; sensitive institutional records are restricted.",
    "sdgRelevance": "",
    "initialConcerns": "Sensitive personal data; school ethics or approval; measurement validity; professional oversight; avoid collecting clinical disclosures.",
    "nextAction": "Narrow to one non-clinical support-service process and obtain campus approval."
  },
  {
    "id": "D16",
    "title": "Employment, Skills, and School-to-Work Transition",
    "type": "Sector",
    "description": "Preparation for work, skills development, recruitment, career guidance, and transition from education to employment.",
    "scopeBoundary": "Career preparation, skills, recruitment, and school-to-work transition; excludes general teaching (D02) and internal MSME operations (D23).",
    "relatedDomainIds": "Related: D02, D23",
    "whyExplore": "Students, graduates, training providers, and employers may reveal measurable skills and transition mismatches.",
    "contextSetting": "Universities, training centers, job fairs, local firms, recruitment channels",
    "stakeholders": "Students, graduates, career offices, trainers, employers, local businesses",
    "processesToExplore": "Skills-requirement analysis, career guidance, job and internship matching, credential records, employer coordination",
    "evidenceBasis": "DOLE, PESO, TESDA, and labor-market sources support relevance; an occupation-specific local mismatch is not validated.",
    "sdgRelevance": "",
    "initialConcerns": "Employer and career-office participation; self-reported skills; changing job requirements; personal-data privacy; outcome follow-up.",
    "nextAction": "Select one occupation or school-to-work transition and confirm employer or career-office participation."
  },
  {
    "id": "D17",
    "title": "Housing, Rental, and Shared Residential Services",
    "type": "Sector",
    "description": "Residential, rental, maintenance, and shared-facility processes affecting tenants, landlords, and communities.",
    "scopeBoundary": "Housing, rental, maintenance, and shared-residential processes; excludes utilities, waste, public safety, and governance when those are the primary problem.",
    "relatedDomainIds": "Related: D06, D08",
    "whyExplore": "Boarding and community-living experiences may reveal observable service and coordination problems.",
    "contextSetting": "Rental housing, dormitories, subdivisions, barangays, shared residential facilities",
    "stakeholders": "Residents, tenants, landlords, homeowners, barangay officials, maintenance personnel",
    "processesToExplore": "Maintenance requests, rental communication, community notices, shared-facility scheduling, residential reporting",
    "evidenceBasis": "Direct observation and interviews in boarding or rental settings are feasible; standardized operational records may be limited.",
    "sdgRelevance": "",
    "initialConcerns": "Private-property and household access; tenant and landlord privacy; differing responsibilities; limited standardized records.",
    "nextAction": "Choose one boarding or rental workflow and confirm both resident and responsible-party access."
  },
  {
    "id": "D18",
    "title": "Environmental Condition Monitoring",
    "type": "Cross-cutting",
    "description": "Systematic observation and measurement of environmental conditions using defined variables, sites, and reference methods.",
    "scopeBoundary": "Validated observation and measurement of environmental conditions; excludes restoration-project management (D25) and utility-service operations (D06).",
    "relatedDomainIds": "Related: D06, D07, D10, D19, D25",
    "whyExplore": "Local conditions can be measured, but a viable study requires a validated variable, reference method, and sampling plan.",
    "contextSetting": "Rivers, watersheds, farms, roadsides, campuses, vulnerable or protected areas",
    "stakeholders": "Residents, environmental officers, schools, farmers, community groups, technical experts",
    "processesToExplore": "Sampling, sensor and field observations, data-quality checks, reporting, trend analysis, threshold assessment",
    "evidenceBasis": "EMB, DOST VI, and UPV technical references provide pathways; the variable-specific dataset and reference method are unconfirmed.",
    "sdgRelevance": "",
    "initialConcerns": "Site permission; sensor calibration; reference laboratory or technical validation; sampling duration; weather exposure; maintenance cost.",
    "nextAction": "Select one environmental variable, site, reference method, sampling period, and total validation cost."
  },
  {
    "id": "D19",
    "title": "Long-Term Climate Adaptation Planning",
    "type": "Cross-cutting",
    "description": "Planning and prioritization of actions that help communities and systems adjust to projected climate impacts over longer time horizons.",
    "scopeBoundary": "Long-term climate planning and adaptation-option prioritization; excludes immediate disaster preparedness (D05) and environmental measurement (D18).",
    "relatedDomainIds": "Related: D05, D18, D25",
    "whyExplore": "The domain is relevant only when narrowed to a planning or resource-allocation decision distinct from preparedness and monitoring.",
    "contextSetting": "Coastal areas, flood-prone communities, agricultural zones, local planning offices",
    "stakeholders": "Local governments, vulnerable communities, environmental planners, researchers",
    "processesToExplore": "Vulnerability assessment, adaptation-option prioritization, local planning, project monitoring, resource allocation",
    "evidenceBasis": "PAGASA and GeoRisk public data provide background; local adaptation-decision evidence is unverified.",
    "sdgRelevance": "",
    "initialConcerns": "Long-term data and evaluation horizon; model complexity; overlap with DRR and environmental monitoring; LGU planning access; policy dependence.",
    "nextAction": "Choose one planning decision with a feasible historical, simulation, or expert-evaluation basis; otherwise drop."
  },
  {
    "id": "D20",
    "title": "Cultural Heritage Documentation and Knowledge Transmission",
    "type": "Specialized",
    "description": "Documentation, safeguarding, and community-controlled transmission of local traditions, oral histories, languages, and cultural knowledge.",
    "scopeBoundary": "Safeguarding and transmitting cultural knowledge with community permission; excludes tourism services (D11) and language-literacy resources (D22) as the primary purpose.",
    "relatedDomainIds": "Related: D11, D22",
    "whyExplore": "Local documentation and knowledge-transmission practices may contain access, continuity, ownership, and validation concerns that can be investigated with community permission.",
    "contextSetting": "One consenting barangay, cultural organization, local heritage office, or school-based local-history setting in Iloilo or Antique",
    "stakeholders": "Cultural knowledge holders, community elders, local historians, cultural organizations, barangay or cultural offices, educators, and learners",
    "processesToExplore": "Existing documentation, consent and ownership practices, transcription, cataloging, access control, community validation, and knowledge transmission",
    "evidenceBasis": "NCCA cultural-inventory and heritage-documentation programs provide background; local community evidence is not yet obtained.",
    "sdgRelevance": "",
    "initialConcerns": "Requires trust-building and consent from elders/communities; cultural sensitivity in handling and presenting oral knowledge; access to community gatekeepers (e.g., barangay or cultural office) is essential before any data collection; risk of misrepresentation if not community-validated.",
    "nextAction": "Select one consenting community and cultural practice, obtain permission, and confirm the revised scope with the submitter."
  },
  {
    "id": "D21",
    "title": "Financial Access and Consumer Service Workflows",
    "type": "Specialized",
    "description": "Access to, understanding of, and support for formal financial services, payments, microfinance, and financial-literacy services.",
    "scopeBoundary": "Consumer access to, understanding of, and support for financial services; excludes credit scoring and internal business management (D23).",
    "relatedDomainIds": "Related: D23, D24",
    "whyExplore": "Local consumers and merchants may reveal barriers in service discovery, onboarding, understanding, and assistance.",
    "contextSetting": "Stores, cooperatives, rural banks, payment agents, schools, community financial-literacy programs",
    "stakeholders": "Consumers, small merchants, cooperative members, financial-literacy educators, financial-service personnel",
    "processesToExplore": "Financial-literacy support, service discovery, onboarding, payment assistance, complaint handling, consumer-side record reconciliation",
    "evidenceBasis": "BSP financial-inclusion and consumer-protection sources provide background; local workflow evidence is unverified.",
    "sdgRelevance": "",
    "initialConcerns": "Financial-data sensitivity; regulated services; trust and informed consent; transaction records unavailable; avoid collecting credentials or balances.",
    "nextAction": "Choose one non-sensitive consumer workflow and define an ethical participant/evidence plan."
  },
  {
    "id": "D22",
    "title": "Local Language and Literacy Resources",
    "type": "Specialized",
    "description": "Reading, writing, translation, comprehension, and preservation of Hiligaynon, Kinaray-a, and other regional-language resources.",
    "scopeBoundary": "Local-language literacy and resource processes; excludes general academic administration (D02) and cultural documentation not centered on language or literacy (D20).",
    "relatedDomainIds": "Related: D02, D14, D20",
    "whyExplore": "Changes under RA 12027 make local-language resource availability, classroom use, and literacy support worth exploring, but a specific local difficulty must be verified with educators and learners.",
    "contextSetting": "Schools, community literacy programs, libraries, cultural organizations, and local-language resource projects",
    "stakeholders": "Students, teachers, local-language advocates or linguists, librarians, DepEd personnel",
    "processesToExplore": "Language mapping, local-language resource cataloging, reading support, transcription, translation assistance, and material evaluation",
    "evidenceBasis": "RA 12027 and education/language-resource sources provide policy background; a local literacy or resource problem is not yet validated. https://lawphil.net/statutes/repacts/ra2024/ra_12027_2024.html",
    "sdgRelevance": "",
    "initialConcerns": "Policy alignment under RA 12027, limited validated datasets, orthography and linguistic expertise, and permissions for copyrighted or community materials",
    "nextAction": "Choose one language/literacy process and local setting, then confirm an educator or linguist and submitter approval."
  },
  {
    "id": "D23",
    "title": "MSME Operations and Digital Commerce",
    "type": "Sector",
    "description": "Day-to-day processes used by micro and small enterprises to manage sales, products, suppliers, customers, and digital channels.",
    "scopeBoundary": "Internal MSME sales, inventory, supplier, customer, and digital-commerce operations; excludes consumer financial access (D21) and whole food-supply chains (D09).",
    "relatedDomainIds": "Related: D09, D16, D21, D24",
    "whyExplore": "Local enterprises provide observable manual and digital workflows without requiring a predetermined solution.",
    "contextSetting": "Stores, market stalls, home-based enterprises, cooperatives, small online shops",
    "stakeholders": "Small-business owners, market vendors, home-based sellers, customers, suppliers, business-support personnel",
    "processesToExplore": "Inventory and stock records, supplier ordering, sales recording, payment reconciliation, customer inquiries, business reporting",
    "evidenceBasis": "DTI and PSA MSME sources support relevance; partner business records and a local bottleneck remain unconfirmed.",
    "sdgRelevance": "",
    "initialConcerns": "Owner availability; inconsistent records; commercial privacy; device and connectivity constraints; avoid sensitive financial or customer data.",
    "nextAction": "Choose one business type and committed partner, then quantify one recurring non-sensitive operational bottleneck."
  },
  {
    "id": "D24",
    "title": "Digital Safety and Data Privacy Practices",
    "type": "Cross-cutting",
    "description": "Safe, lawful, and responsible handling of personal data, accounts, devices, and online interactions when security or privacy is the primary research concern.",
    "scopeBoundary": "Security or privacy must be the primary research problem; excludes treating it only as a requirement of another domain. All studies must be controlled and authorized.",
    "relatedDomainIds": "Related: D12, D13, D21, D23",
    "whyExplore": "Local practices and support workflows can be examined safely through controlled and authorized studies.",
    "contextSetting": "Schools, campuses, public offices, local businesses, community organizations, online groups",
    "stakeholders": "Students, educators, parents or guardians, office staff, business owners, data-protection personnel",
    "processesToExplore": "Privacy-notice comprehension, consent, account-security practices, scam recognition and reporting, incident reporting, permissions, data retention",
    "evidenceBasis": "NPC, DICT, and CICC materials provide background; a specific local user or workflow problem is not yet validated.",
    "sdgRelevance": "",
    "initialConcerns": "Participant privacy and informed consent; access to incident logs is restricted; institutional authorization; controlled testing only; no unauthorized access.",
    "nextAction": "Choose one controlled awareness, usability, reporting, or privacy workflow and obtain institutional authorization."
  },
  {
    "id": "D25",
    "title": "Mangrove Restoration/Environment and Conservation Operations",
    "type": "Specialized",
    "description": "Planning, coordination, documentation, and management of mangrove restoration activities and their project-level outcomes.",
    "scopeBoundary": "Mangrove-restoration planning, coordination, field records, and project reporting; excludes scientific environmental-condition measurement as the primary purpose (D18) and generic waste or water-service operations.",
    "relatedDomainIds": "Related: D06, D07, D10, D18, D19",
    "whyExplore": "Mangrove-restoration projects involve field records, activity coordination, survival tracking, and reporting processes that may warrant investigation when one site and responsible organization are accessible.",
    "contextSetting": "One verified mangrove-restoration site in Iloilo; Leganes Integrated Katunggan Ecopark is a documented candidate, but research access is unconfirmed",
    "stakeholders": "Site managers, LGU environment offices, DENR or BFAR personnel, fisherfolk, conservation organizations, community partners, volunteers, and researchers",
    "processesToExplore": "Restoration planning, planting-site records, project-level survival and growth tracking, field-data collection, activity and volunteer coordination, reporting, and decision-making",
    "evidenceBasis": "Official documentation confirms mangrove-restoration activity at Leganes Integrated Katunggan Ecopark. The submitter also reports a possible personal route to relevant records or evidence, but the exact datasets, ownership, coverage, quality, format, and research-use permission remain to be verified. https://www.bmb.gov.ph/the-katunggan-ecopark/",
    "sdgRelevance": "",
    "initialConcerns": "Formal stakeholder participation, site permission, and data access are not yet confirmed; details of the known contact and available evidence remain undocumented; field conditions; ecological validation needs; imagery or equipment costs and licensing; overlap with D18.",
    "nextAction": "Decide whether the focus is restoration management or scientific condition measurement; if measurement is primary, merge with D18. Document the known contact\u2019s organization or role, confirm participation and site access, and identify the exact obtainable datasets."
  }
];
